version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: miner-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: miner_game
      MYSQL_USER: miner_user
      MYSQL_PASSWORD: miner_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - miner-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: miner-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - miner-network

  # 后端应用
  app:
    build: .
    container_name: miner-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: miner_game
      DB_USER: miner_user
      DB_PASSWORD: miner_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your_super_secret_jwt_key_change_in_production
      JWT_EXPIRES_IN: 7d
      JWT_REFRESH_EXPIRES_IN: 30d
    depends_on:
      - mysql
      - redis
    networks:
      - miner-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：phpMyAdmin数据库管理
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: miner-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - miner-network

  # 可选：Redis Commander管理界面
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: miner-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - miner-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  miner-network:
    driver: bridge